/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototype_Company.GUI;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.util.ArrayList;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;   
import javax.swing.JOptionPane;
/**
 *
 * @author kneiv
 */
public class AddDeliverer extends javax.swing.JFrame {

    /**
     * Creates new form AddDeliverer
     */
    public AddDeliverer() {
        initComponents();
    
        //initialize GUI 
        
        try{
           
           Connection conn = DriverManager.getConnection("jdbc:h2:C:\\Users\\kneiv\\ArtTranssc_database" , "root" , "Pokemon123");
           Statement stmt = conn.createStatement();
           
           String CarmodelQuery = "Select model from car";
           int CarID;
           String CarModel;
           
           ResultSet execute = stmt.executeQuery(CarmodelQuery);
        
           while(execute.next()){
               Car.addItem(execute.getString("Model"));
           }
    }
        
     catch(Exception e){
           System.out.println(e);
       }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        Car = new javax.swing.JComboBox<>();
        Car_indicator = new javax.swing.JLabel();
        AddDriverButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Title_deliverer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Imie");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        surname.setText("Nazwisko");

        phoneNumber.setText("Telefon");

        Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarActionPerformed(evt);
            }
        });

        Car_indicator.setText("Pojazd");

        AddDriverButton.setText("Dodaj Pracownika");
        AddDriverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDriverButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Powrot");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Title_deliverer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Title_deliverer.setText("Dodaj Kierowce");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Car_indicator)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Car, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(name)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddDriverButton)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Title_deliverer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_deliverer)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Car_indicator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDriverButton)
                    .addComponent(BackButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
private void insertDriver(){
     String firstname, lastname, phone, carName;
        int DelivererID = 0, EmployeeID = 0, CarID = 0;
        
        ArrayList Query = new ArrayList();
        
        if (name.getText().isEmpty()||surname.getText().isEmpty()|| phoneNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Dane nie zostaly wpisane, sprobuj ponownie.");
            return;
        }
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:h2:C:\\Users\\kneiv\\ArtTranssc_database" , "root" , "Pokemon123");
            Statement stmt = conn.createStatement();
           String delivererID = "select delivererid from deliverer";
           String employeeID = "select employeeid from employee";
           String carID = "select carid from car where model = ";
            
           
           // add data to arraylist
           
           firstname = String.valueOf("'" + name.getText() + "'");
            System.out.println(firstname);
           lastname = String.valueOf("'" + surname.getText() + "'");
            System.out.println(lastname);
           phone = String.valueOf("'" + phoneNumber.getText() + "'");
            System.out.println(phone);
            
            
             ResultSet execute = stmt.executeQuery(employeeID);
            //Retrieve last known employeeID;
            while(execute.next()){
                EmployeeID = execute.getInt("employeeID") + 1;
                System.out.println(EmployeeID);
                
            }
            Query.add(EmployeeID);
            execute = stmt.executeQuery(delivererID);
           
            
            Query.add(firstname);
            Query.add(lastname);
            Query.add(phone);
            
            // retrieve last known Deliverer ID
            while(execute.next()){
               DelivererID = execute.getInt("delivererID") + 1;
               System.out.println(DelivererID);
               
            }
            Query.add(DelivererID);
            //Retrieve choosen carID
           
           carName = String.valueOf("'" + Car.getSelectedItem() + "'");
             
           carID += carName;
            System.out.println(carID);
            execute = stmt.executeQuery(carID);
           
           //Retrieve carID by its model
           
           while(execute.next()){
               CarID = execute.getInt("carid");
               
           }
           Query.add(CarID);
            
            
            
            System.out.println(Query);
        
        //Create final query
        
        String sql = "insert into employee values (" + Query.get(0) + "," + Query.get(1) +"," + Query.get(2) + "," + Query.get(3)+ ")";
        
            System.out.println(sql);
        
        
       String sql2 = " insert into deliverer values (" + Query.get(0) + ", " + Query.get(4) + ", " + Query.get(5) + ")";
       
       
            System.out.println(sql2);
         stmt.execute(sql);
         stmt.execute(sql2);
      
            
                JOptionPane.showMessageDialog(null, "Kierowca dodany pomyslnie");
        }
        
       
        
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "Blad przy dodawaniu kierowcy");
             System.out.println(e);
         }
}

    private void AddDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDriverButtonActionPerformed
       insertDriver();
    }//GEN-LAST:event_AddDriverButtonActionPerformed

    private void CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainPage_Logged_in xd = new MainPage_Logged_in();
        xd.setVisible(rootPaneCheckingEnabled);
        xd.setTitle("ArtTranssc Delivery Manager");
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDeliverer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDeliverer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDeliverer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDeliverer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDeliverer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDriverButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> Car;
    private javax.swing.JLabel Car_indicator;
    private javax.swing.JLabel Title_deliverer;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
